### ISSUE TITLE
Choose open licenses for the project

### ISSUE THREAD

**Issue by Ludee** [rl-institut/wwf_dashboard#37]
Since this going to be published and we want others to reuse the informations and graphics it would be good to add suitable open licenses for the project and the website.

Suggested open licenses:

- project source code (this repo) -> `AGPL-3.0-or-later`
reason: If reused new developments must be open as well
attribution: © Reiner Lemoine Institut

- underlying data -> check original data licenses

- website and final graphics -> `CC-BY-4.0`
reason: If reused and republished it needs to be attributed and linked to the original website
attribution: ["WWF Climate Dashboard"](https://wwf.rl-institut.de/) © [Reiner Lemoine Institut](https://reiner-lemoine-institut.de/) | [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/)

**Comment by Ludee** [comment]
Add the material license to each info page with a new section:

**Download und Weiternutzung**

Titel des Werkes on ["WWF Climate Dashboard"](https://wwf.rl-institut.de/) © [Reiner Lemoine Institut](https://reiner-lemoine-institut.de/) | [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/)

Bei Weiternutzung müssen Sie den Titel und die Rechteinhaberin des Werks nennen, einschließlich eines Hyperlinks zum Werk und der gewählten Lizenz.

**Comment by henhuy** [comment]
done - thx @Ludee
